In [1]:
import numpy as np

In [2]:
arr=np.array([1,3,2,4])
print(arr)

[1 3 2 4]


In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr[0])

1


## 1D Array

In [5]:
a=np.array([1,2,3,4,5,6])
a.ndim #returns dimension

1

## 2D Array

In [6]:
b=np.array([[1,2,3],
            [4,5,6]])

b.ndim

2

## 3D Array

In [7]:
c=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print(c)
c.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3

## Shaping a Numpy Array

In [8]:
num1=np.array([1,2,3,4,5,6,7,8,9,10])
print(num1)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
num1.shape

(10,)

In [10]:
num1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
num1.shape

(10,)

In [13]:
num1_cp=num1.reshape(2,5)
num1_cp

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
num1_cp.shape

(2, 5)

In [15]:
num1_cp.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
num1_cp

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])